### ISSUE TITLE
Accessing from outside network via domain?

### ISSUE THREAD

**Issue by karneaud** [mageddo/dns-proxy-server#104]
Does this services allow docker containers to be accessed outside the container network by other devices using a domain rather than host's ip/port ??

**Comment by mageddo** [comment]
If by devices you mean others computers, smartphones, etc. then no, DPS  will help you to solve containers using domain instead of ip's across containers  and accross host machine and it's containers, it's not possible to access a container by it's hostname from another machine only using DPS. 

To achieve this you can use nginx to centralize requests on the machine where the containers are running then install DPS on each device and register the hostnames using DPS manual entries pointing to the nginx machine

Now if you really want a distributed cluster solving containers hostnames accross machines in the cluster  then I advice to take a look at docker swarm or kubernates
