### ISSUE TITLE
No way to specify upstream/remote DNS server port 

### ISSUE THREAD

**Issue by ammmze** [mageddo/dns-proxy-server#121]
I'd like to include the Consul DNS server as one of the remote name servers, but it looks like it only accepts the IP address as an array of numbers. Ideally we should be able to include the port in the remote dns server settings. Honestly I'd prefer to be able to just configure it as `"remoteDnsServers": ["172.16.33.33:8600"]`, which means you'd need to parse the port out because it looks like the parameters you pass into your function to add the host is the ip address and then the port as a separate parameter.

**Comment by mageddo** [comment]
I agree we would migrate the remoteDnsServers variable to an string instead of array of ints.

> I'd like to include the Consul DNS server as one of the remote name servers

You current problem is that you can't specify the port or the remote server as a array is not suitable to you?

**Comment by ammmze** [comment]
My current hold up is not being able specify the port. Migration to a string would just be a nice to have

**Comment by mageddo** [comment]
### What is expected 
__:bulb:  A way to specify the remote servers port__

* [ ] If not port were specified then `53` have to be assumed
* [ ] Change json contract to specify Remover Server using string instead of array of bytes

current contract

```json
{
  "remoteDnsServers": [[208,67,222,222]],
}
```

proposed contract

```json
{
  "remoteDnsServers": ["208.67.222.222", "208.67.222.223:5353"],
}
```

__:bulb: Change hostname ip contract__

Contract today is array of bytes, as discussed before use a string instead of the array may be more clear to read and meaningful when the port have to be specified, as the remote server will change to the string format it makes sense to change that field also

**Comment by mageddo** [comment]
DPS was released and the docs updated, see http://mageddo.github.io/dns-proxy-server/2.14/en/3-configuration/

**Comment by mageddo** [comment]
@ammmze thanks for your contribution, feel to make any report when you need

**Comment by ammmze** [comment]
Awesome! I'm glad to see you also switched the other instances of IP addresses to strings 🙂 thanks a bunch
