### ISSUE TITLE
Docker image upgrade

### ISSUE THREAD

**Issue by mageddo** [mageddo/dns-proxy-server#143]
### What is expected

DPS can be upgraded to debian 10 and start to use the slim image using a lightweight image

**Comment by ricardoper** [comment]
Hello,

Why not a **static compile** and use `FROM scratch`?

**Sizes**:
scratch - 11MB
debian:stable-slim - 80MB
debian:8 - 167MB

Take a look at CoreDNS...

Regards.

**Comment by mageddo** [comment]
thanks for the suggestion @ricardoper 

I never heard about scratch image, I will take a look then make some tests

**Comment by ricardoper** [comment]
`scratch` is a special image because this is a empty image. No files inside...

I don't know all the parts of this project, but I think that you can compile statically with some extra flags. So no system dependencies, no dependencies at all, no system required on your container. The binary it's a bit larger but you reduce the container size a lot.

Less than 20MB for this container project will be a extreme plus.

You are welcome.

**Comment by ricardoper** [comment]
The app needs access to SSL certificates?

In the next hours/days I will create a pull request for lighter containers.

I already have a functional example. Less than 11MB for AMD64 containers without SSL certificates.

**Comment by mageddo** [comment]
> The app needs access to SSL certificates?

Actually not

**Comment by mageddo** [comment]
As said, DPS is dependent on some linux commands, I will keep this issue focused on upgrade and migrate the images to `debian:10-slim` as migrate to scratch image will requires a additional effort

**Comment by ricardoper** [comment]
I read all messages and understood... Sorry for that.

If you need my help, please don't hesitate to tell me.
