### ISSUE TITLE
is this project abandoned? should we be looking for alternative?

### ISSUE THREAD

**Issue by pschiffe** [mageddo/dns-proxy-server#430]

**Comment by hellodanylo** [comment]
There is a fix for the Docker issue in an unmerged PR https://github.com/mageddo/dns-proxy-server/pull/432
If nothing changes, we can probably fork.

**Comment by cenk1cenk2** [comment]
For now I just built it as a fork with the propsed patch.

You can access it here:
https://hub.docker.com/repository/docker/cenk1cenk2/dns-proxy-server/tags?page=1&ordering=last_updated

And the repository is at: https://github.com/cenk1cenk2/dns-proxy-server

**Comment by mageddo** [comment]
Hey, the project is not abandoned, but I confess that hadn't time to focus on it  at the latest months. I will keep dedicating some amount of my time weekly on the project, also appreciate contributions specially for fixes like #432 .

That said, I've released the new version with the fix for #431 

Thanks for the patience, sorry for the inconvenience.
