### ISSUE TITLE
DNS missing HOSTNAMES env from neighbors container

### ISSUE THREAD

**Issue by andrezaycev** [mageddo/dns-proxy-server#55]
Hello. 

We have issue:
if some containers started later than dns-proxy (for example longstart database), dns is not learning their HOSTNAMES variable (detected missing in proxy log)

We fix it over force-restart dns-proxy container in the end.

Tell me please how often dns-proxy have refresh HOSTNAMES vars from neighbor? Maybe possible to add parameter for it (reduce to 1 min for example)?

**Comment by mageddo** [comment]
It happens only at SO startup or at any moment? I think I experienced this bug before but I can't confirm it. 

Actually there isn't a refresh interval DPS uses [Docker API](http://github.com/docker/engine-api/) library events 

https://github.com/mageddo/dns-proxy-server/blob/4a4de3c/events/docker/DockerEvents.go#L43

Maybe I missed some configuration in that API

**Comment by andrezaycev** [comment]
Detect it on startup. i'm use docker-machine for develop. It's happenning when containers autostart after virtualbox starting

**Comment by mageddo** [comment]
Thanks for the feedback, I think a figure out a problem in that code.

* When dns-proxy-server starts it gets a list of all started containers
* Then it register itself at Docker events
* I think there is a gap between the containers list and the events registration, If some container starts at this time it will not be registered. That's simple to fix so we can fix it and see what happens.
* Basically we need to register in Docker events first, then list the containers, it can provide duplicated records but that is not a problem

Please confirm If this issue is intermittent (don't happens every time even in the same situation)

**Comment by mageddo** [comment]
After that  I can try to update the Docker client API.

**Comment by mageddo** [comment]
Please checkout   [the new release](https://github.com/mageddo/dns-proxy-server/releases/tag/2.2.3) with a possible fix, then let me know if it works for you. If not then send me a log file dump since machine startup

**Comment by andrezaycev** [comment]
Thanks man. Will check in dynamic nearest week. Will write feedback later
